name: app_ventas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.3.0
  pdf: ^3.10.4
  printing: ^5.10.4
  path_provider: ^2.1.1
  image_picker: ^1.0.4 # Para seleccionar imágenes
  flutter_image_compress: ^2.1.0 # Para comprimir y redimensionar imágenes
  image: ^4.1.0   # ← Añade esto
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
