name: Build iOS
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: echo "✅ Runner listo: $(sw_vers)"
      - run: sudo xcodebuild -license accept || echo "⚠️ Licencia ya aceptada"
      - run: echo "✅ Xcode version: $(xcodebuild -version | head -2)"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.0'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build ipa --release --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: build/ios/ipa/*.ipa
