name: Build iOS V3
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcodebuild -license accept
      - run: rm -rf ~/.cocoapods/repos
      - run: pod setup --silent
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.0'
      - run: flutter pub get
      - run: flutter build ipa --release --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: build/ios/ipa/*.ipa
